services:
    metamodels.attribute_timestamp.factory:
        class: MetaModels\AttributeTimestampBundle\Attribute\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
            - '@event_dispatcher'
        tags:
          - { name: metamodels.attribute_factory }

    metamodels.attribute_timestamp.backend.encode_property_value_from_widget_listener:
        class: MetaModels\AttributeTimestampBundle\EventListener\BootListener
        tags:
            - {
                name: kernel.event_listener,
                event: 'dc-general.view.contao2backend.encode-property-value-from-widget',
                method: handleEncodePropertyValueFromWidget
              }

    metamodels.attribute_timestamp.backend.decode_property_value_for_widget_listener:
        class: MetaModels\AttributeTimestampBundle\EventListener\BootListener
        tags:
            - {
                name: kernel.event_listener,
                event: 'dc-general.view.contao2backend.decode-property-value-for-widget',
                method: handleDecodePropertyValueForWidgetEvent
              }
